//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.ProductEDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDNProductDBEntities : DbContext
    {
        public SDNProductDBEntities()
            : base("name=SDNProductDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoriesContent> CategoriesContents { get; set; }
        public virtual DbSet<ProductsAndService> ProductsAndServices { get; set; }
        public virtual DbSet<TaxCodesAndRate> TaxCodesAndRates { get; set; }
    }
}
