//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.PurchasingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseInvoice()
        {
            this.DebitNotes = new HashSet<DebitNote>();
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
        }
    
        public int ID { get; set; }
        public string PI_No { get; set; }
        public System.DateTime PI_Date { get; set; }
        public Nullable<System.DateTime> PI_Pmt_Due_Date { get; set; }
        public string Our_PO_No { get; set; }
        public Nullable<bool> Exc_Inc_GST { get; set; }
        public int Sup_Id { get; set; }
        public Nullable<int> Ship_to_address { get; set; }
        public Nullable<decimal> PI_Tot_bef_Tax { get; set; }
        public Nullable<decimal> PI_GST_Amt { get; set; }
        public Nullable<decimal> PI_Tot_aft_Tax { get; set; }
        public string PI_TandC { get; set; }
        public Nullable<bool> BusinessExpenses { get; set; }
        public Nullable<byte> PI_Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitNote> DebitNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
    }
}
