//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.ManufacturingEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfMaterial
    {
        public int ProductAssemblyID { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> PerAssemblyQty { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ComponentLevel { get; set; }
    }
}
