//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.ManufacturingEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventory
    {
        public int ProductInventoryID { get; set; }
        public string Product { get; set; }
        public string Inventory_Location { get; set; }
        public Nullable<int> Qty_Available { get; set; }
    }
}
