//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseQuotationDetail
    {
        public int ID { get; set; }
        public int PQ_ID { get; set; }
        public string PQ_No { get; set; }
        public string PandS_Code { get; set; }
        public string PandS_Name { get; set; }
        public Nullable<int> PQ_Qty { get; set; }
        public Nullable<decimal> PQ_Price { get; set; }
        public Nullable<decimal> PQ_Amount { get; set; }
        public Nullable<decimal> PQ_Discount { get; set; }
        public string GST_Code { get; set; }
        public Nullable<decimal> GST_Rate { get; set; }
    
        public virtual PurchaseQuotation PurchaseQuotation { get; set; }
    }
}
