//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.Sales.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditNote
    {
        public int ID { get; set; }
        public string CN_No { get; set; }
        public Nullable<System.DateTime> CN_Date { get; set; }
        public string Cus_DN_No { get; set; }
        public Nullable<System.DateTime> Cus_DN_Date { get; set; }
        public Nullable<int> Salesman { get; set; }
        public Nullable<decimal> Cus_DN_Amount { get; set; }
        public int Cus_Id { get; set; }
        public int SI_Id { get; set; }
        public Nullable<byte> CN_Status { get; set; }
        public string CN_Reason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
