//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInOutCard
    {
        public int ID { get; set; }
        public Nullable<int> SI_PI { get; set; }
        public string Cus_Sup_Name { get; set; }
        public string Trans_Type { get; set; }
        public string Trans_No { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> QtyIn { get; set; }
        public Nullable<int> Qtyout { get; set; }
        public Nullable<System.DateTime> Trans_Date { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> Inc_GST { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
