//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.CashBank.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDNCashBankDBEntities : DbContext
    {
        public SDNCashBankDBEntities()
            : base("name=SDNCashBankDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountsTransaction> AccountsTransactions { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<CashAndBank> CashAndBanks { get; set; }
        public virtual DbSet<CashAndBankDetail> CashAndBankDetails { get; set; }
        public virtual DbSet<CashAndBankHistory> CashAndBankHistories { get; set; }
        public virtual DbSet<CashAndBankStatement> CashAndBankStatements { get; set; }
        public virtual DbSet<CashAndBankTransaction> CashAndBankTransactions { get; set; }
        public virtual DbSet<CashFlowCalendar> CashFlowCalendars { get; set; }
    }
}
