//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.Sales.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingAddress
    {
        public int ID { get; set; }
        public int EntityId { get; set; }
        public string EntityType { get; set; }
        public string Ship_to_line1 { get; set; }
        public string Ship_to_line2 { get; set; }
        public string Ship_to_city { get; set; }
        public string Ship_to_state { get; set; }
        public string Ship_to_country { get; set; }
        public string Ship_to_post_code { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
