//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterModule
    {
        public int ID { get; set; }
        public string Module_Name { get; set; }
        public int Module_Id { get; set; }
        public int Tab_Id { get; set; }
        public string Tab_Name { get; set; }
        public int Order_Id { get; set; }
    }
}
