//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.PurchasingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseQuotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseQuotation()
        {
            this.PurchaseQuotationDetails = new HashSet<PurchaseQuotationDetail>();
        }
    
        public int ID { get; set; }
        public string PQ_No { get; set; }
        public System.DateTime PQ_Date { get; set; }
        public Nullable<int> PQ_Valid_for { get; set; }
        public Nullable<bool> Exc_Inc_GST { get; set; }
        public int Sup_Id { get; set; }
        public Nullable<int> Ship_to_address { get; set; }
        public Nullable<decimal> PQ_Tot_bef_Tax { get; set; }
        public Nullable<decimal> PQ_GST_Amt { get; set; }
        public Nullable<decimal> PQ_Tot_aft_Tax { get; set; }
        public string PQ_TandC { get; set; }
        public Nullable<bool> PQ_Conv_to_PO { get; set; }
        public Nullable<bool> PQ_Conv_to_PI { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseQuotationDetail> PurchaseQuotationDetails { get; set; }
    }
}
