//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsIdentity
    {
        public int ID { get; set; }
        public string Acc_Type_Name { get; set; }
        public Nullable<int> Acc_Type_Code { get; set; }
    }
}
