//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustedDebitNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdjustedDebitNote()
        {
            this.AdjustedDebitNoteDetails = new HashSet<AdjustedDebitNoteDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string DebitNoteNumber { get; set; }
        public Nullable<System.DateTime> DebitNoteDate { get; set; }
        public Nullable<decimal> DebitNoteAmount { get; set; }
        public string AdjustDebitNoteNumber { get; set; }
        public Nullable<System.DateTime> AdjustDebitNoteDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustedDebitNoteDetail> AdjustedDebitNoteDetails { get; set; }
    }
}
