//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessExpensesDetail
    {
        public int ID { get; set; }
        public int PI_ID { get; set; }
        public Nullable<decimal> PI_Amount { get; set; }
        public string GST_Code { get; set; }
        public Nullable<decimal> GST_Rate { get; set; }
        public string Bus_Expenses_Desc { get; set; }
        public string Bus_Expenses_Acc_Name { get; set; }
    
        public virtual BusinessExpens BusinessExpens { get; set; }
    }
}
