//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public int ID { get; set; }
        public int JO_ID_ { get; set; }
        public string JO_No { get; set; }
        public Nullable<System.DateTime> JO_Date { get; set; }
        public Nullable<int> Acc_ID { get; set; }
        public Nullable<decimal> JO_Debit_ { get; set; }
        public Nullable<decimal> JO_Credit_ { get; set; }
        public Nullable<int> JO_CreatedBy_ { get; set; }
        public Nullable<int> JO_ModifiedBy_ { get; set; }
        public Nullable<System.DateTime> JO_ModifiedDate_ { get; set; }
        public Nullable<bool> JO_IsDeleted_ { get; set; }
    
        public virtual Journal Journal { get; set; }
    }
}
