//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
        public int ID { get; set; }
        public string J_No { get; set; }
        public Nullable<System.DateTime> J_Date { get; set; }
        public Nullable<int> J_CreatedBy { get; set; }
        public Nullable<int> J_ModifiedBy { get; set; }
        public Nullable<System.DateTime> J_ModifiedDate { get; set; }
        public Nullable<bool> J_IsDeleted { get; set; }
        public Nullable<System.DateTime> J_CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
    }
}
