//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PandSSoldToCustomer
    {
        public int ID { get; set; }
        public int Cus_Id { get; set; }
        public string Cus_Name { get; set; }
        public Nullable<byte> Year { get; set; }
        public Nullable<byte> Quarter { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Inv_No { get; set; }
        public Nullable<System.DateTime> Inv_Date { get; set; }
        public string PandS_Code { get; set; }
        public string PandS_Name { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Inc_GST { get; set; }
        public string PandS_Type { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
