//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCount
    {
        public int ID { get; set; }
        public string PandS_Code { get; set; }
        public string PandS_Name { get; set; }
        public Nullable<int> SysQty { get; set; }
        public Nullable<int> CountQty { get; set; }
        public Nullable<int> Difference { get; set; }
        public Nullable<decimal> Average_Cost { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Adjusted_Amount { get; set; }
        public string Stock_count_no { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<short> StockType { get; set; }
        public Nullable<int> PSID { get; set; }
    }
}
