//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.DebitNotes = new HashSet<DebitNote>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.SuppliersBusinessCards = new HashSet<SuppliersBusinessCard>();
        }
    
        public int ID { get; set; }
        public string Sup_Name { get; set; }
        public string Sup_Inactive { get; set; }
        public string Sup_Company_Reg_no { get; set; }
        public Nullable<int> Sup_Credit_Limit_Days { get; set; }
        public Nullable<decimal> Sup_Credit_Limit_Amount { get; set; }
        public string Sup_Telephone { get; set; }
        public string Sup_Fax { get; set; }
        public string Sup_Email { get; set; }
        public string Sup_Contact_Person { get; set; }
        public string Sup_GST_Reg_No { get; set; }
        public Nullable<bool> Sup_Charge_GST { get; set; }
        public string Sup_Remarks { get; set; }
        public string Sup_Bill_to_line1 { get; set; }
        public string Sup_Bill_to_line2 { get; set; }
        public string Sup_Bill_to_city { get; set; }
        public string Sup_Bill_to_state { get; set; }
        public string Sup_Bill_to_country { get; set; }
        public string Sup_Bill_to_post_code { get; set; }
        public string Sup_Ship_to_line1 { get; set; }
        public string Sup_Ship_to_line2 { get; set; }
        public string Sup_Ship_to_city { get; set; }
        public string Sup_Ship_to_state { get; set; }
        public string Sup_Ship_to_country { get; set; }
        public string Sup_Ship_to_post_code { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsRefreshed { get; set; }
        public Nullable<System.DateTime> RefreshedDate { get; set; }
        public Nullable<int> TaxId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitNote> DebitNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliersBusinessCard> SuppliersBusinessCards { get; set; }
    }
}
