//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersHistory
    {
        public int ID { get; set; }
        public int Sup_Id { get; set; }
        public string Sup_Name { get; set; }
        public Nullable<decimal> Col1_Amount { get; set; }
        public Nullable<decimal> Col2_Amount { get; set; }
        public Nullable<decimal> Col3_Amount { get; set; }
        public Nullable<decimal> Total_Purchase_Amount { get; set; }
        public Nullable<byte> Year1 { get; set; }
        public Nullable<byte> Year2 { get; set; }
        public Nullable<byte> Quarter { get; set; }
        public Nullable<bool> C_Inc_GST { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
