//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDetail
    {
        public int ID { get; set; }
        public int Sup_Id { get; set; }
        public string Sup_Name { get; set; }
        public string Sup_Inactive { get; set; }
        public string Sup_Company_Reg_no { get; set; }
        public string Sup_Type { get; set; }
        public string Sup_Salesman { get; set; }
        public Nullable<int> Sup_Credit_Limit_Days { get; set; }
        public Nullable<decimal> Sup_Credit_Limit_Amount { get; set; }
        public Nullable<decimal> Sup_Discount { get; set; }
        public string Sup_Telephone { get; set; }
        public string Sup_Fax { get; set; }
        public string Sup_Email { get; set; }
        public string Sup_Contact_Person { get; set; }
        public string Sup_GST_Reg_No { get; set; }
        public Nullable<bool> Sup_Charge_GST { get; set; }
        public string Sup_Remarks { get; set; }
        public string Sup_Bill_to_line1 { get; set; }
        public string Sup_Bill_to_line2 { get; set; }
        public string Sup_Bill_to_city { get; set; }
        public string Sup_Bill_to_state { get; set; }
        public string Sup_Bill_to_country { get; set; }
        public string Sup_Bill_to_post_code { get; set; }
        public string Sup_Ship_to_line1 { get; set; }
        public string Sup_Ship_to_line2 { get; set; }
        public string Sup_Ship_to_city { get; set; }
        public string Sup_Ship_to_state { get; set; }
        public string Sup_Ship_to_country { get; set; }
        public string Sup_Ship_to_post_code { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
