//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public Nullable<int> OverdueDays { get; set; }
        public Nullable<System.DateTime> PromisedDate { get; set; }
    }
}
