//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UndeliveredSalesOrderWithDeposit
    {
        public int ID { get; set; }
        public Nullable<int> C_ID { get; set; }
        public string USalesOrder_No { get; set; }
        public Nullable<System.DateTime> USalesOrder_Date { get; set; }
        public Nullable<decimal> USalesOrder_Amount { get; set; }
        public Nullable<decimal> USalesOrderDeposit_Amount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
