//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.Customers.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersBusinessCard
    {
        public int ID { get; set; }
        public Nullable<int> Cus_Id { get; set; }
        public string Cus_Bus_Card_Name { get; set; }
        public byte[] Cus_Bus_Card_Photos { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
