//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.PurchasingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitNote
    {
        public int ID { get; set; }
        public string DN_No { get; set; }
        public Nullable<System.DateTime> DN_Date { get; set; }
        public string Sup_CN_No { get; set; }
        public Nullable<System.DateTime> Sup_CN_Date { get; set; }
        public Nullable<decimal> Sup_CN_Amount { get; set; }
        public int Sup_Id { get; set; }
        public int PI_Id { get; set; }
        public string DN_Reason { get; set; }
        public Nullable<byte> DN_Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
