//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.PurchasingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int ID { get; set; }
        public string PO_No { get; set; }
        public System.DateTime PO_Date { get; set; }
        public System.DateTime PO_Del_Date { get; set; }
        public Nullable<bool> Exc_Inc_GST { get; set; }
        public int Sup_Id { get; set; }
        public Nullable<int> Ship_to_address { get; set; }
        public Nullable<decimal> PO_Tot_bef_Tax { get; set; }
        public Nullable<decimal> PO_GST_Amt { get; set; }
        public Nullable<decimal> PO_Tot_aft_Tax { get; set; }
        public string PO_TandC { get; set; }
        public Nullable<bool> PO_Conv_to_PI { get; set; }
        public Nullable<byte> PO_Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
