//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.ProductEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceDetail
    {
        public int ID { get; set; }
        public int PI_ID { get; set; }
        public string PI_No { get; set; }
        public string PandS_Code { get; set; }
        public string PandS_Name { get; set; }
        public Nullable<int> PI_Qty { get; set; }
        public Nullable<decimal> PI_Price { get; set; }
        public Nullable<decimal> PI_Amount { get; set; }
        public Nullable<decimal> PI_Discount { get; set; }
        public string GST_Code { get; set; }
        public Nullable<decimal> GST_Rate { get; set; }
        public string Bus_Expenses_Desc { get; set; }
        public string Bus_Expenses_Acc_Name { get; set; }
    
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
    }
}
