//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.SettingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<int> Acc_Type { get; set; }
        public Nullable<decimal> Acc_Open_Bal { get; set; }
        public Nullable<decimal> Acc_Cur_Bal { get; set; }
        public Nullable<System.DateTime> Acc_Year_to_date { get; set; }
        public string Acc_Inactive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
