//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.SettingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesContent
    {
        public int ID { get; set; }
        public Nullable<int> Cat_Id { get; set; }
        public Nullable<decimal> Content_Limit { get; set; }
        public string Cat_Contents { get; set; }
        public Nullable<bool> Set_Default { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Predefined { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
