//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.SettingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public int ID { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Reg_No { get; set; }
        public string Comp_GST_Reg_No { get; set; }
        public Nullable<System.DateTime> Comp_GST_Reg_Date { get; set; }
        public Nullable<System.DateTime> Comp_GST_Dereg_Date { get; set; }
        public string Comp_Tel { get; set; }
        public string Comp_Fax { get; set; }
        public string Comp_Email { get; set; }
        public Nullable<System.DateTime> Comp_year_start_date { get; set; }
        public Nullable<System.DateTime> Comp_year_end_date { get; set; }
        public byte[] Comp_Logo { get; set; }
        public string Software_Ser_No { get; set; }
        public string Comp_Bill_to_line1 { get; set; }
        public string Comp_Bill_to_line2 { get; set; }
        public string Comp_Bill_to_city { get; set; }
        public string Comp_Bill_to_state { get; set; }
        public string Comp_Bill_to_country { get; set; }
        public string Comp_Bill_to_post_code { get; set; }
        public string Comp_Ship_to_line1 { get; set; }
        public string Comp_Ship_to_line2 { get; set; }
        public string Comp_Ship_to_city { get; set; }
        public string Comp_Ship_to_state { get; set; }
        public string Comp_Ship_to_country { get; set; }
        public string Comp_Ship_to_post_code { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
