//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.SettingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxCodesAndRate
    {
        public int ID { get; set; }
        public string Tax_Name { get; set; }
        public string Tax_Description { get; set; }
        public string Tax_Code { get; set; }
        public decimal Tax_Rate { get; set; }
        public string Tax_Inactive { get; set; }
        public Nullable<bool> Tax_Default { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Predefined { get; set; }
    }
}
