//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.SettingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermsAndCondition
    {
        public int ID { get; set; }
        public string Cat_Name { get; set; }
        public string Cat_Code { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string Cat_Content { get; set; }
    }
}
