//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PandSHistory
    {
        public int ID { get; set; }
        public string PandS_Code { get; set; }
        public string P_S_Name { get; set; }
        public Nullable<decimal> Col1_Sal_Amount { get; set; }
        public Nullable<decimal> Col1_Pur_Amount { get; set; }
        public Nullable<decimal> Col2_Sal_Amount { get; set; }
        public Nullable<decimal> Col2_Pur_Amount { get; set; }
        public Nullable<decimal> Col3_Sal_Amount { get; set; }
        public Nullable<decimal> Col3_Pur_Amount { get; set; }
        public string PandS_Cat1 { get; set; }
        public string PandS_Cat2 { get; set; }
        public Nullable<byte> Year1 { get; set; }
        public Nullable<byte> Year2 { get; set; }
        public Nullable<byte> Quarter { get; set; }
        public Nullable<bool> Inc_GST { get; set; }
        public string PandS_Type { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
