//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersPaymentDueDay
    {
        public int ID { get; set; }
        public int Cus_Id { get; set; }
        public string Cus_Name { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> C1_30Days { get; set; }
        public Nullable<decimal> C31_60Days { get; set; }
        public Nullable<decimal> C61_90Days { get; set; }
        public Nullable<decimal> GreaterThen_90Days { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
