//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.CashBank.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashAndBankDetail
    {
        public int ID { get; set; }
        public int Cus_Id { get; set; }
        public string Cus_Name { get; set; }
        public Nullable<byte> Year { get; set; }
        public Nullable<byte> Quarter { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Cash_Cheq_No { get; set; }
        public Nullable<System.DateTime> Cash_Cheq_Date { get; set; }
        public Nullable<decimal> Cash_Cheq_Amount { get; set; }
        public string SO_SI_No { get; set; }
        public Nullable<System.DateTime> SO_SI_Date { get; set; }
        public Nullable<decimal> SO_SI_Amount { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
