//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopCustomer
    {
        public int ID { get; set; }
        public int Cus_Id { get; set; }
        public string Cus_Name { get; set; }
        public Nullable<byte> Year { get; set; }
        public Nullable<byte> Quarter { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<bool> Inc_GST { get; set; }
        public Nullable<decimal> Sales_Amount { get; set; }
        public Nullable<decimal> Sales_Percentage { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
        public Nullable<decimal> Payment_Percentage { get; set; }
        public Nullable<decimal> Profit_Amount { get; set; }
        public Nullable<decimal> Profit_Percentage { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
