//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.PurchasingsEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastSelectionHistory
    {
        public int ID { get; set; }
        public int Screen_Id { get; set; }
        public string Screen_Name { get; set; }
        public string Last_Selection { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public Nullable<int> Last_UpdatedBy { get; set; }
    }
}
