//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlowCalendar
    {
        public int ID { get; set; }
        public Nullable<byte> Year1 { get; set; }
        public Nullable<byte> Year2 { get; set; }
        public Nullable<byte> Cash_Flow_Month { get; set; }
        public Nullable<decimal> Amt_Mon { get; set; }
        public Nullable<decimal> Amt_Tue { get; set; }
        public Nullable<decimal> Amt_Wed { get; set; }
        public Nullable<decimal> Amt_Thu { get; set; }
        public Nullable<decimal> Amt_Fri { get; set; }
        public Nullable<decimal> Amt_Sat { get; set; }
        public Nullable<decimal> Amt_Sun { get; set; }
        public string Row_Type { get; set; }
        public string View_Type { get; set; }
        public Nullable<decimal> Payment_To_Cus { get; set; }
        public Nullable<decimal> Payment_To_Sup { get; set; }
        public Nullable<decimal> LV_Net_Amt { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
