//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.PurchasingsEDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SDNPurchasingDBEntities : DbContext
    {
        public SDNPurchasingDBEntities()
            : base("name=SDNPurchasingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseQuotation> PurchaseQuotations { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<PurchaseQuotationDetail> PurchaseQuotationDetails { get; set; }
        public virtual DbSet<LastSelectionHistory> LastSelectionHistories { get; set; }
        public virtual DbSet<DebitNote> DebitNotes { get; set; }
        public virtual DbSet<CashAndBankTransaction> CashAndBankTransactions { get; set; }
    
        public virtual ObjectResult<SP_PurchaseInvoiceList_Result> SP_PurchaseInvoiceList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PurchaseInvoiceList_Result>("SP_PurchaseInvoiceList");
        }
    }
}
