//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.CashBank.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashAndBank
    {
        public int ID { get; set; }
        public Nullable<int> Acc_Id { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<decimal> Opening_Balance { get; set; }
        public Nullable<decimal> Current_Balance { get; set; }
        public Nullable<System.DateTime> Year_to_Date { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
