//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.ProductEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoiceDetail
    {
        public int ID { get; set; }
        public int SI_ID { get; set; }
        public string SI_No { get; set; }
        public string PandS_Code { get; set; }
        public string PandS_Name { get; set; }
        public Nullable<int> SI_Qty { get; set; }
        public Nullable<decimal> SI_Price { get; set; }
        public Nullable<decimal> SI_Amount { get; set; }
        public Nullable<decimal> SI_Discount { get; set; }
        public string GST_Code { get; set; }
        public Nullable<decimal> GST_Rate { get; set; }
    
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
