//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.Sales.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int ID { get; set; }
        public string Date_Format { get; set; }
        public string Number_Format { get; set; }
        public Nullable<byte> Decimal_Places { get; set; }
        public string Currency_Code { get; set; }
        public string Starting_Sales_Inv_No { get; set; }
        public string Name_to_Print_Sales_Invoice { get; set; }
        public string Def_Cash_Bank_Acc { get; set; }
        public Nullable<bool> Show_Amount_Inc_GST { get; set; }
        public Nullable<bool> Show_Account_Balance { get; set; }
        public Nullable<bool> Cus_Detail_Allow_Chg_Limit { get; set; }
        public Nullable<bool> PS_Detail_Allow_Chg_Act { get; set; }
        public Nullable<bool> Allow_to_Create_Sales_Inv { get; set; }
        public Nullable<bool> Show_PS_Name { get; set; }
        public Nullable<bool> Show_PS_Name_Desc { get; set; }
        public Nullable<bool> Allow_Edit_PS_Name_Desc { get; set; }
        public Nullable<bool> Allow_Edit_PS_Price { get; set; }
        public Nullable<bool> Allow_Edit_Discount { get; set; }
        public Nullable<bool> Hide_Discount_Column { get; set; }
        public Nullable<bool> PS_Qty_Jump_Next_Line { get; set; }
        public Nullable<bool> Print_PS_Name { get; set; }
        public Nullable<bool> Print_PS_Name_Desc { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Print_Del_Sales_Inv { get; set; }
    }
}
