//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDN.Sales.EDM
{
    using System;
    
    public partial class PRC_SalesInvoiceList_Result
    {
        public int ID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> ExcIncGST { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime InvoiceDateDateTime { get; set; }
        public int Sup_ID { get; set; }
        public Nullable<decimal> InvoiceAmountValue { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> CashChequeAmount { get; set; }
        public Nullable<System.DateTime> CashChequeDateDate { get; set; }
        public string CashChequeNo { get; set; }
        public Nullable<System.DateTime> CreditNoteDateDate { get; set; }
        public string CreditNoteNo { get; set; }
        public Nullable<decimal> CreditNoteAmount { get; set; }
        public string t { get; set; }
    }
}
